<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LHTU05CG6422NZD" name="runners.Runner_Housecall_SocialGovReferralAssistanceProgram" tests="1" failures="0" timestamp="22 Jul 2019 11:04:06 GMT" time="89.896" errors="1">
  <testcase name="feature" time="89.896" classname="runners.Runner_Housecall_SocialGovReferralAssistanceProgram">
    <error type="cucumber.runtime.CucumberException" message="cucumber.runtime.CucumberException: Arity mismatch: Step Definition &#039;stepDefinitions.Step_Housecalls_SocialGovReferralAssistanceProgram.new_table_schema_exist_in_database(String) in file:/C:/Users/hn1001/workspace/NSF_UI/target/test-classes/&#039; with pattern [^verify that fields exists in (.*) (.*) and the (.*) for the (.*) should be valid$] is declared with 1 parameters. However, the gherkin step has 4 arguments [&quot;IndividualPlanDemographic&quot;, &quot;IndividualPlanDemographic&quot;, &quot;VARCHAR20&quot;, &quot;HouseCallsProgram&quot;]. 
Step: Then verify that fields exists in &quot;IndividualPlanDemographic&quot; &quot;IndividualPlanDemographic&quot; and the &quot;VARCHAR20&quot; for the &quot;HouseCallsProgram&quot; should be valid">
      <![CDATA[cucumber.runtime.CucumberException: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.Step_Housecalls_SocialGovReferralAssistanceProgram.new_table_schema_exist_in_database(String) in file:/C:/Users/hn1001/workspace/NSF_UI/target/test-classes/' with pattern [^verify that fields exists in (.*) (.*) and the (.*) for the (.*) should be valid$] is declared with 1 parameters. However, the gherkin step has 4 arguments ["IndividualPlanDemographic", "IndividualPlanDemographic", "VARCHAR20", "HouseCallsProgram"]. 
Step: Then verify that fields exists in "IndividualPlanDemographic" "IndividualPlanDemographic" and the "VARCHAR20" for the "HouseCallsProgram" should be valid
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.Step_Housecalls_SocialGovReferralAssistanceProgram.new_table_schema_exist_in_database(String) in file:/C:/Users/hn1001/workspace/NSF_UI/target/test-classes/' with pattern [^verify that fields exists in (.*) (.*) and the (.*) for the (.*) should be valid$] is declared with 1 parameters. However, the gherkin step has 4 arguments ["IndividualPlanDemographic", "IndividualPlanDemographic", "VARCHAR20", "HouseCallsProgram"]. 
Step: Then verify that fields exists in "IndividualPlanDemographic" "IndividualPlanDemographic" and the "VARCHAR20" for the "HouseCallsProgram" should be valid
	at cucumber.runtime.StepDefinitionMatch.arityMismatch(StepDefinitionMatch.java:102)
	at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:60)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	... 26 more
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runners.Runner_Housecall_SocialGovReferralAssistanceProgram -->
